#ifndef RESOURCES_H
#define RESOURCES_H
//#############################################################################

// ICON
#define IDI_APP_ICON 2001

// STRINGTABLE
#define IDS_STR_EMPTY							6000
#define IDS_STR_APP_NAME						6001
#define IDS_STR_APP_HELP						6002
#define IDS_STR_APP_ABOUT						6003
#define IDS_STR_ERROR_REG_CLASS					6004

#define IDS_STR_GROUPBOX_VALUE					6005
#define IDS_STR_LABEL_VALUE						6006
#define IDS_STR_PUSHBUTTON_CONVERT				6007

#define IDS_STR_GROUPBOX_SINGLE					6008
#define IDS_STR_LABEL_SINGLE_BINARY_SIGN		6009
#define IDS_STR_LABEL_SINGLE_BINARY_EXP			6010
#define IDS_STR_LABEL_SINGLE_BINARY_MANTISSA	6011
#define IDS_STR_PUSHBUTTON_COPY_SINGLE_BINARY	6012
#define IDS_STR_LABEL_SINGLE_HEX				6013
#define IDS_STR_PUSHBUTTON_COPY_SINGLE_HEX		6014
#define IDS_STR_LABEL_SINGLE_IEEE754			6015
#define IDS_STR_PUSHBUTTON_COPY_SINGLE_IEEE754	6016
#define IDS_STR_CHECKBOX_EXP_SINGLE				6017

#define IDS_STR_GROUPBOX_DOUBLE					6018
#define IDS_STR_LABEL_DOUBLE_BINARY_SIGN		6019
#define IDS_STR_LABEL_DOUBLE_BINARY_EXP			6020
#define IDS_STR_LABEL_DOUBLE_BINARY_MANTISSA	6021
#define IDS_STR_PUSHBUTTON_COPY_DOUBLE_BINARY	6022
#define IDS_STR_LABEL_DOUBLE_HEX				6023
#define IDS_STR_PUSHBUTTON_COPY_DOUBLE_HEX		6024
#define IDS_STR_LABEL_DOUBLE_IEEE754			6025
#define IDS_STR_PUSHBUTTON_COPY_DOUBLE_IEEE754	6026
#define IDS_STR_CHECKBOX_EXP_DOUBLE				6027

#define IDS_STR_GROUPBOX_INFO					6028
#define IDS_STR_PUSHBUTTON_HELP					6029
#define IDS_STR_PUSHBUTTON_ABOUT				6030

#define IDS_STR_GROUPBOX_RESULTS				6031
#define IDS_STR_PUSHBUTTON_COPY_RESULTS			6032
#define IDS_STR_PUSHBUTTON_SAVE_RESULTS			6033
#define IDS_STR_RESULTS_COPY_OK					6034
#define IDS_STR_RESULTS_COPY_FAIL				6035
#define IDS_STR_RESULTS_SAVE_OK					6036
#define IDS_STR_RESULTS_SAVE_FAIL				6037

#define IDS_STR_GROUPBOX_HISTORY				6038
#define IDS_STR_COMBOBOX_HISTORY				6039

#define IDS_STR_APP_HELP_TEXT					6040
#define IDS_STR_APP_ABOUT_TEXT					6041

#define IDS_STR_CONVERTER_RESULTS_STATUS_OK		6042
#define IDS_STR_CONVERTER_RESULTS_STATUS_FAIL	6043


//#############################################################################
#endif